name: TalkingHand
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - opencv=4.5.2=py38haa244fe_0
  - pillow=8.1.2=py38h9273828_1
  - pip=21.1.1=pyhd8ed1ab_0
  - pip:
    - gtts==2.2.2
    - numpy==1.19.5
    - playsound==1.2.2
    - pyttsx3==2.90
    - tensorflow==2.5.0
prefix: C:\Users\lenovo\miniconda3\envs\TalkingHand
